version: '3.8'

services:
  servicio1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8062:80"  # Cambié esto a 8062 para coincidir con el puerto de tu ejemplo anterior
    volumes:
      - ./2/template2:/usr/local/apache2/htdocs/  # Asegúrate de que tu ruta esté correcta
    networks:
      - localnet

  servicio2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - "3306:3306"
    networks:
      - localnet

networks:
  localnet:
